---
title: "Lab 01 - Programación en R"
output:
  html_document:
    css: ./ds_labs.css
    toc: yes
    toc_float: yes
    fig_caption: no
    seal : False
    includes:
      after_body: insert-logo.html
  pdf_document:
    toc: yes
---


<div class="title-logo"></div>

```{r packages_setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
knitr::opts_chunk$set(fig.width=8, fig.height=6) 
```


## Ejercicio 1

Escribe una función que devuelva $k$ números, donde cada número es
la suma de $n$ números escogidos al azar entre 1 y 100 (con reemplazamiento), divido entre n.

Pinta un histograma con los resultados de $k=10000$ para $n=1$, $n=2$, $n=10$ y $n=100$.
Pista: puedes usar la función `hist()`.

¿Qué observas?


## Ejercicio 2

Utiliza la ayuda de la función `replicate()` para conocer su funcionamiento.
Resuelve el Ejercicio 1 sin usar un bucle (si es que lo habías usado).


## Ejercicio 3

La base de datos `mtcars` de R contiene información extraída de la *1974 Motor Trend US magazine* acerca de 10 aspectos de diseño de rendimiento de 32 vehículos. 
Usando esta base de datos, calcula 

**Pregunta 1.** La diferencia entre el consumo medio de los vehículos de transmisión automática y los de transmisión manual.

**Pregunta 2.** La misma diferencia pero únicamente para vehículos de más de 3000 lbs.

Pista: la ayuda ?mtcars te puede ser útil

## Ejercicio 4

Utilizando un bucle `for` y un `if`, suma los números pares entre 1 y 100 (ambos incluidos).

## Ejercicio 5

Calcula la ganancia esperada de la estrategia de ruleta que consiste en apostar 10 euros siempre al rojo.

Para ello:

  - Crea una función llamada `spin()` que devuelva un número muestreado al azar entre 0 y 36 (ambos incluidos).
  - Crea otra función llamada `compute_gain()` que tenga un argumento `q` referido a la cantidad de dinero de la apuesta, con valor por defecto de 10. Esta función, ha de generar un tirada de la ruleta y, en función del resultado, calcular la ganancia y devolverla. Recuerda que
  
    * Los números (1,3,7,9,19,21,23,25,27,12,14,16,18,30,32,34,36) tienen color rojo.
    * Los números (2,4,6,8,20,22,24,26,28,11,13,15,17,29,31,33,35) tienen color negro.
    * El cero no tiene color.
    
  - Por último, crea un bucle que simule 10.000 partidas de la ruleta, almacena la ganancia generada en cada una y calcula la media. ¿Qué observas?
  
## Ejercicio 6

Repite el ejercicio anterior pero esta vez evaluando la estrategia de apostar todo al número 17. ¿Qué conclusión extraes?
